### ISSUE TITLE
eduGAIN SAML metadata refresh starts by failing at each refresh interval

### ISSUE THREAD

**Issue by jouvin** [indigo-iam/iam#884]
Looking at the IAM logs, I saw that at every SAML metadata refresh cycle for eduGAIN, the first attempt to download the metadata fails with a strange SSL error and then works a few minutes after. The typical sequence is:

```
2024-11-09 08:55:59.071 ERROR 7 --- [ metadata-fetch] o.o.s.m.provider.HTTPMetadataProvider    : Error retrieving metadata from https://metadata.federation.renater.fr/edugain/main/main-idps-edugain-metadata.xml

javax.net.ssl.SSLException: SSLSession was invalid: Likely implicit handshake failure: Set system property javax.net.debug=all for details
        at org.opensaml.ws.soap.client.http.TLSProtocolSocketFactory.verifyHostname(TLSProtocolSocketFactory.java:275)
        at org.opensaml.ws.soap.client.http.TLSProtocolSocketFactory.createSocket(TLSProtocolSocketFactory.java:194)
        at org.springframework.security.saml.trust.httpclient.TLSProtocolSocketFactory.createSocket(TLSProtocolSocketFactory.java:97)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at org.opensaml.saml2.metadata.provider.HTTPMetadataProvider.fetchMetadata(HTTPMetadataProvider.java:250)
        at org.opensaml.saml2.metadata.provider.FileBackedHTTPMetadataProvider.fetchMetadata(FileBackedHTTPMetadataProvider.java:154)
        at org.opensaml.saml2.metadata.provider.AbstractReloadingMetadataProvider.refresh(AbstractReloadingMetadataProvider.java:258)
        at org.opensaml.saml2.metadata.provider.AbstractReloadingMetadataProvider$RefreshMetadataTask.run(AbstractReloadingMetadataProvider.java:516)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)

2024-11-09 08:55:59.071  WARN 7 --- [ metadata-fetch] o.o.s.m.p.FileBackedHTTPMetadataProvider : Problem reading metadata from remote source, processing existing backup file: /tmp/metadata18329544024266345722xml
2024-11-09 08:56:03.445  INFO 7 --- [ metadata-fetch] .s.m.p.AbstractReloadingMetadataProvider : New metadata succesfully loaded for 'https://metadata.federation.renater.fr/edugain/main/main-idps-edugain-metadata.xml'
2024-11-09 08:56:03.445  INFO 7 --- [ metadata-fetch] .s.m.p.AbstractReloadingMetadataProvider : Next refresh cycle for metadata provider 'https://metadata.federation.renater.fr/edugain/main/main-idps-edugain-metadata.xml' will occur on '2024-11-09T20:56:02.377Z' ('2024-11-09T20:56:02.377Z' local time)
```

It doesn't have a concrete impact on the instance as it always succeeds at the end but this looks weird. I only looked in detail to this error recently but I have always seen it as far as I remember...

Any advice welcome on how to troubleshoot this issue...

**Comment by DonaldChung-HK** [comment]
https://github.com/spring-attic/spring-security-saml/issues/233 Probably the unexpected behavior described here about opensaml library.

**Comment by jouvin** [comment]
As for me, the problem was related to a missing certificate in `cacerts` for HARICA CA and it seems to be fixed in 1.14 (probably due to an updated `cacerts`), without the need to manager `cacerts` with `egi-trustanchors` as introduced by https://github.com/indigo-iam/egi-trust-anchors-container/pull/7. 

I think this issue could be closed.

**Comment by enricovianello** [comment]
I agree.
I think also these lines of this commit helped resolving this issue:
https://github.com/indigo-iam/iam/commit/50fa0e97ab594e854aba8e15a07e0975a0e7da18#diff-a6b15dcdca4cca1f3f22134eea12d644963b1a8217192dd49da324878fcaed8aL493-L498
and this fix has been included within v1.14.0.
Have you seen this error again ? @jouvin
